function [ASSIGNTABLE] = lockdown(MASTER, ASSIGNTABLE,NOES,ALLDISTS, NTH,ROWIN,COLIN)
%prune via NOEs
if (1)
  myROWIN = 1:size(MASTER,1);
  myCOLIN = 1:size(MASTER,2);
  MASTER(ROWIN,COLIN) = ASSIGNTABLE;
  NP = NOE_PRUNE(MASTER,NOES,ALLDISTS,NTH, myROWIN,myCOLIN);
  NP = NP(ROWIN,COLIN);
else
  NP = NOE_PRUNE(ASSIGNTABLE,NOES,ALLDISTS,NTH,ROWIN,COLIN);
end

ASSIGNTABLE=and(NP,NP);
